- name: PT3-T0
  types:
    - GR
  command: C:\nyanzTV\BonRecTest.exe --space <space> --driver C:\nyanzTV\BonDriver_PT3-T0.dll --output - --channel <channel>
  decoder: C:\nyanzTV\arib-b25-stream-test.exe
  isDisabled: false

- name: PT3-S0
  types:
    - BS
    - CS
  command: C:\nyanzTV\BonRecTest.exe --space <space> --driver C:\nyanzTV\BonDriver_PT3-S0.dll --output - --channel <channel>
  decoder: C:\nyanzTV\arib-b25-stream-test.exe
  isDisabled: false
